### ISSUE TITLE
执行之后，原文件未进行压缩

### ISSUE THREAD

**Issue by wadezha** [JacksonTian/loader-builder#10]
现在使用./node_modules/loader-builder/bin/builder ./views/ / 压缩之后，min 文件不会合并压缩，还是原文件 ，记得以前是会将原文件压缩成最小文件，不知道是什么问题

**Comment by JacksonTian** [comment]
min文件会跳过压缩。因为min文件基本已经是压缩过了，重复压缩会浪费构建时间。
