### ISSUE TITLE
缓存之前编译的结果

### ISSUE THREAD

**Issue by alsotang** [JacksonTian/loader-builder#5]
现在单次编译的时候是不是比原来快一点了？

我看在一次编译中，如果一个文件被编译过了，那么第二次的用时是 0ms。

能不能让多次编译也可以重用结果？在 loader-builder 里面弄个 .cache 文件夹，如果文件 md5 在这个里面找得到，就直接用里面内容的结果。
现在每次编译 jquery 都是 3000ms。我看 webpack 是有这方面缓存的。只编译改动的部分。

**Comment by JacksonTian** [comment]
像jQuery这种都不会改的文件，加上.min.js作为结尾，然后就不编译了。直接使用。
