### ISSUE TITLE
构建 bootstrap css 出错

### ISSUE THREAD

**Issue by alsotang** [JacksonTian/loader-builder#6]
怀疑跟这一句的 baseurl 参数有关
https://github.com/JacksonTian/loader-builder/blob/master/lib/builder.js#L180

bootstrap 里面写的 url 路径是 `../` 的相对路径，导致这里出错。

![image](https://cloud.githubusercontent.com/assets/1147375/13905091/a027a7a6-eef0-11e5-8bac-55f5ff51b20f.png)

**Comment by JacksonTian** [comment]
把文件改为绝对路径吧。现在loader-builder能解决background-image: url的事情了。

**Comment by alsotang** [comment]
人家bootstrap是个外部库，这边简单的 url 相关引用，应该是你这边做兼容吧？

2016-03-21 10:28 GMT+08:00 Jackson Tian notifications@github.com:

**Comment by luoyjx** [comment]
我也出现这个问题。。。

**Comment by luoyjx** [comment]
好吧，我直接用的min版

**Comment by JacksonTian** [comment]
现在的版本已经支持min文件跳过，url()相对路径了。

**Comment by alsotang** [comment]
已在 nodeclub 使用 2.4.1 版本

**Comment by zkboys** [comment]
这个问题最终到底怎么解决呢？

**Comment by JacksonTian** [comment]
升级就解决了
